### ISSUE TITLE
OutOfMemoryException.

### ISSUE THREAD

**Issue by jbrinkman** [nothingmn/AGENT.Contrib#2]
If you allow one of the sample apps to run for extended period you will eventually hit an outofmemory exception.  This occurs in the RandomNotification method of SimpleNotifications.  If anyone follows this example they will inherit the same issue.

**Comment by nothingmn** [comment]
This is the intended behavior, for now.  The SimpleNotifications is used to test the system to see how many notifications can be received (and to test the UI's ability to adapt to many notifications), --to see the breaking points.

My initial tests were that the emulator was able to receive close to 400 notifications before throwing this exception. 

Once the actual notification SDK is published from the AGENT team, we will write a new Notification provider and use their API; the current Contrib implementation is used to abstract that dependency away...  :)

Thanks for the heads up!

**Comment by jbrinkman** [comment]
Understood.  Might be a good idea to include comments in SimpleNotifications regarding the memory issue so that people know not to use this as a baseline example.
